import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Index.module.scss'
import { Carousel } from '../components/Carousel'
import { Shutter } from '../components/Shutter'

const Index = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      </main>

      <footer className={styles.footer}>
      <a
          href="https://github.com/jason-warner"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/github.svg" alt="Github Logo" width={33} height={33} />
          </span>
        </a>
          Jason Warner
          <a
          href="https://codepen.io/jason-warner"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/codepen.svg" alt="CodePen Logo" width={33} height={33} />
          </span>
        </a>
          
      </footer>
    </div>
  )
}

export default Index;
